---
title: "DA410_Assignment1_GRAHN"
author: "Jason Grahn"
date: "1/5/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

# Q 2.1
```{r}
A <- matrix(c(4,2,3,7,5,8), 
            nrow = 2, 
            ncol = 3,
            byrow = TRUE)

B <- matrix(c(3,-2,4,6,9,-5), 
            nrow = 2, 
            ncol = 3,
            byrow = TRUE)

is.matrix(A)
is.matrix(B)
```

```{r}
# find A + B 
A + B

# and A - B
A - B
```

```{r}
# find A'A 
t(A) %*% A

# and AA'
A %*% t(A)
```

# Q 2.2
```{r}
# Find (A + B)' 
t(A + B)

# and A' + B' 
t(A) + t(B)

# and compare them, thus illustrating (2.15).
(t(A + B)) - (t(A) + t(B))
```

```{r}
# Show that (A')' = A, thus illustrating (2.6).
A
t(t(A))

A - t(t(A))
```

# Q 2.3(a)
```{r}
A <- matrix(c(1, 3, 2, -1), 
            nrow = 2, 
            ncol = 2, 
            byrow = 2)
B <- matrix(c(2,0,1,5), 
            nrow = 2, 
            ncol = 2, 
            byrow = TRUE)

#Find AB 
A*B

#and BA.
B*A
```

# Q 2.14
```{r}
A <- matrix(c(1,3,2,2,0,-1),
            nrow = 2,
            ncol = 3,
            byrow = TRUE)

B <- matrix(c(1,2,0,1,1,0),
            nrow = 3,
            ncol = 2,
            byrow = TRUE)

C <- matrix(c(2,1,1,5,-6,-4),
            nrow = 2,
            ncol = 3,
            byrow = TRUE)
A
B
C
```

```{r}
# Find AB 
A %*% B

# and CB. 
C %*% B

# Are they equal? 
A %*% B - C %*% B
# subtracting one from the other shows that they are equal.

# What is the rank of A, B, and C?
Matrix::rankMatrix(A)[1]
Matrix::rankMatrix(B)[1]
Matrix::rankMatrix(C)[1]
#The rank of each matrix A, B, and C is 2.
```

# Q 2.18
```{r}
A <- matrix(c(1,-1,1,2,1,0,1,-1,-1),
            nrow = 3,
            ncol = 3,
            byrow = TRUE)
A
#Normalize the columns of A by dividing each column by its length; denote the resulting matrix by C.
vec1 <- A[,1]
vec2 <- A[,2]
vec3 <- A[,3]

len1 <- sqrt(1^2 + 2^2 + 1^2)
len2 <- sqrt((-1)^2 + 1^2 + (-1)^2)
len3 <- sqrt(1^2 + 0^2 + (-1)^2)

C <- matrix(c(vec1/len1, vec2/len2, vec3/len3),
       nrow = 3,
       ncol = 3,
       byrow = FALSE)

#Show that C is an orthogonal matrix, that is, C'C = C C = I.
round(crossprod(C), 
      digits = 1)

```

