---
title: "Project 06"
author: "Jason Grahn"
date: "2/19/2019"
output: word_document
---

```{r setup}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(broom)
library(knitr)
library(ggfortify)
```

```{r data load}
probe <- read.table(here::here("assignment07/T3_6_PROBE.DAT"))  %>% 
  rename(subject_number = V1,
         y1 = V2, # no explanation
         y2 = V3, # no explanation
         y3 = V4, # no explanation
         y4 = V5, # no explanation
         y5 = V6,) %>% 
  mutate(subject_number = factor(subject_number))# no explanation

head(probe, 3) %>% knitr::kable()
# given the data has higher numbers, we should scale this
```

```{r}
probe_pca <- probe %>% 
  nest() %>% 
  mutate(pca = map(data, ~ prcomp(.x %>% select(-subject_number), 
                                  center = TRUE, 
                                  scale = TRUE)),
         pca_aug = map2(pca, data, ~augment(.x, data = .y)))

probe_pca
```

```{r}
var_exp <- probe_pca %>% 
  unnest(pca_aug) %>% 
  summarize_at(.vars = vars(contains("PC")), 
               .funs = funs(var)) %>% 
  gather(key = pc, 
         value = variance) %>% 
  mutate(var_exp = variance/sum(variance),
         cum_var_exp = cumsum(var_exp),
         pc = str_replace(pc, ".fitted", ""))

var_exp
```

```{r}
var_exp %>% 
  rename(
    `Variance Explained` = var_exp,
    `Cumulative Variance Explained` = cum_var_exp
  ) %>% 
  gather(key = key, value = value, `Variance Explained`:`Cumulative Variance Explained`) %>% 
  ggplot(aes(pc, value, group = key)) + 
  geom_point() + 
  geom_line() + 
  facet_wrap(~key, scales = "free_y") +
  theme_bw() +
  lims(y = c(0, 1)) +
  labs(y = "Variance",
       title = "Variance explained by each principal component")
```

