---
title: "Project 06"
author: "Jason Grahn"
date: "2/19/2019"
output: word_document
---

```{r setup}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(magrittr)
library(dplyr)
```

```{r data load}
probe <- read.table(here::here("assignment07/T3_6_PROBE.DAT"))  %>% 
  rename(subject_number = V1,
         y1 = V2, # no explanation
         y2 = V3, # no explanation
         y3 = V4, # no explanation
         y4 = V5, # no explanation
         y5 = V6,) %>% 
  mutate(subject_number = factor(subject_number))# no explanation

head(probe, 3)
# given the data has higher numbers, we should scale this
```

```{r variable selection}
# First, variable selection
probe.var <- probe %>% select(y1, y2, y3, y4)
probe.subjects <- probe %>% select(subject_number)
```

Do a principle component analysis of the data in Table 3.6 (page 79)
You may use R to solve this part (NO built-in function).

```{r}
# scale, center, and apply PCA 
probe.pca <- prcomp(probe.var,
                    center = TRUE,
                    scale. = TRUE) 
# print method
print(probe.pca)

# summary method
summary(probe.pca)
```

```{r}
# plot method
## borrowing some plotting code from 
## https://towardsdatascience.com/principal-component-analysis-pca-101-using-r-361f4c53a9ff 
screeplot(probe.pca, type = "l", main = "Screeplot of the PCs")
abline(h = 0.5, 
       col="red", 
       lty=5)
legend("topright", 
       legend=c("Eigenvalue = .5"),
       col=c("red"), 
       lty=5, 
       cex=0.6)

cumpro <- round(cumsum(probe.pca$sdev^2 / sum(probe.pca$sdev^2)),4)
plot(cumpro[0:4], 
     xlab = "PC #", 
     ylab = "Amount of explained variance", 
     main = "Cumulative variance plot")
abline(v = 3, col="blue", lty=5)
abline(h = 0.95, col="blue", lty=5)
legend("topleft", 
       legend=c("Cut-off @ PC3"),
       col=c("blue"), lty=5, cex=0.6)

plot(probe.pca$x[,1],
     probe.pca$x[,2], 
     xlab="PC1 (73.12%)", 
     ylab = "PC2 (14.58%)", 
     main = "PC1 / PC2 - plot")
```

```{r}
# Predict PCs
predict(probe.pca, 
        newdata = tail(log(probe.var), 2))


round(sum(summary(probe.pca)$importance[2,]), 2)
```



